---
permalink: install-linux/task_restart_unified_manager.html 
sidebar: sidebar 
keywords: restart, unified manager 
summary: Potrebbe essere necessario riavviare Unified Manager dopo aver apportato modifiche alla configurazione. 
---
= Riavvio di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario riavviare Unified Manager dopo aver apportato modifiche alla configurazione.

*Cosa ti serve*

È necessario disporre dell'accesso utente root al server Red Hat Enterprise Linux o CentOS su cui è installato Unified Manager.

.Fasi
. Accedere come utente root al server sul quale si desidera riavviare il servizio Unified Manager.
. Arrestare il servizio Unified Manager e il software MySQL associato nell'ordine indicato:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
`systemctl stop mysqld`

. Avviare Unified Manager nell'ordine indicato:
+
`systemctl start mysqld`

+
`systemctl start ocie`

+
`systemctl start ocieau`

+

NOTE: `mysqld` È un programma daemon necessario per avviare e arrestare il server MySQL.


