---
permalink: include/upgrade-path.html 
sidebar: sidebar 
keywords: supported upgrade path, upgrade path, n-2, which versions can be upgraded 
summary: Percorso di upgrade supportato 
---
= Percorso di aggiornamento supportato per le versioni di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager supporta un percorso di aggiornamento specifico per ciascuna versione.

Non tutte le versioni di Unified Manager possono eseguire un aggiornamento in-place alle versioni successive. Gli aggiornamenti di Unified Manager sono limitati a un modello N-2, il che significa che un aggiornamento può essere eseguito solo nelle 2 release successive su tutte le piattaforme. Ad esempio, è possibile eseguire un aggiornamento a Unified Manager 9.12 solo da Unified Manager 9.10 e 9.11.

Se si utilizza una versione precedente a quella supportata, l'istanza di Unified Manager deve essere prima aggiornata a una delle versioni supportate, quindi aggiornata alla versione corrente.

Ad esempio, se la versione installata è OnCommand 9.5 e si desidera eseguire l'aggiornamento alla versione più recente di Active IQ Unified Manager 9.12, seguire una sequenza di aggiornamenti.

.Esempio di percorso di aggiornamento:
. Upgrade di OnCommand Unified Manager 9.5 -> Active IQ Unified Manager 9.7.
. Aggiornamento 9.7 -> 9.9.
. Aggiornamento 9.9 -> 9.11.
. Aggiornamento 9.11 -> 9.12.


Per ulteriori informazioni sulla matrice dei percorsi di aggiornamento, vedere questa sezione https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_the_upgrade_path_for_Active_IQ_Unified_Manager_versions["Articolo della Knowledge base (KB)"].
